name: Radio Recorder Parallel

on:
  schedule:
    - cron: '0 * * * *' # כל שעה עגולה
  workflow_dispatch:

env:
  TZ: 'Asia/Jerusalem' # חשוב מאוד לשמות הקבצים ולשעות

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Record Streams
        run: python main.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          tag_name: rec-${{ github.run_id }}
          name: הקלטות - שעה ${{ github.run_number }}
          files: "*.mp3"
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
